name: flutter_flow_chart
description: draw a flow chart diagram with different kind of customizable elements. Dashboards can be saved for later use.
version: 3.0.0
homepage: https://github.com/alnitak/flutter_flow_chart

environment:
  sdk: ">=2.17.6 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  # https://pub.dev/packages/uuid
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:

